version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=helloworld
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    network_mode: host

  test:
    build: .
    container_name: test
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - postgres
    volumes:
      - /.ivy2:/.ivy2
      - .:/skunk-flyway:z
    working_dir: /skunk-flyway
    network_mode: host
    # Sources bashrc to run startup scripts to wait for dependencies
    command: test
